[build]
  command = "npm run build:frontend"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_BASE_URL = "/.netlify/functions/api"
  # GOOGLE_API_KEY = "SUA_CHAVE_GOOGLE_AQUI_PARA_BUILD_SE_NECESSARIO"
  # SPREADSHEET_ID = "SEU_ID_PLANILHA_AQUI_PARA_BUILD_SE_NECESSARIO"